### ISSUE TITLE
Crash on load with the GOG version of StS

### ISSUE THREAD

**Issue by ProbablyGallium** [brianyee/MeleeMod#5]
## Steps to Reproduce
- Attempt to load the game with BaseMod, STSLib, and MeleeMod enabled with the GOG version of the game

## Expected Behavior
- The game boots.

## Actual Behavior
- The game doesn't even load, throwing out errors in the debug console.

I'm not sure what information is relevant so [here](https://hastebin.com/ayarokujuc.makefile) is my debug console.
Thank you in advance!

**Comment by beeyee0401** [comment]
In your StS installation direction, do you have the desktop-1.0.jar in the same folder as ModTheSpire as well?

Sorry if my instructions for usage were incorrect, as this was all done using the Steam version.

**Comment by ProbablyGallium** [comment]
Yep, `desktop-1.0.jar` and `ModTheSpire.jar` are in the same folder.

**Comment by beeyee0401** [comment]
I very much believe that this issue has something to do with the file structure being incorrect, because the error that is being outputted is that a method from desktop-1.0.jar doesn't exist.

Can you list the paths of your relevant files? 
- MeleeMod
- StSLib
- BaseMod
- ModTheSpire
- desktop-1.0.jar

**Comment by ProbablyGallium** [comment]
MeleeMod, StSLib and BaseMod are all in `C:\GOG Games\Slay the Spire\mods`.
ModTheSpire and desktop-1.0.jar are in `C:\GOG Games\Slay the Spire`.

**Comment by beeyee0401** [comment]
I asked around on the modding discord, and no one seems to know what this issue is. As I do not have the GOG version of the game, I will not be looking into this at this time. I'll update the README to specify this is for the Steam version specifically.

Sorry for the inconvenience, maybe in the future, if it's on sale, I'll buy it from GOG. But more than likely, it'll stay unsupported.

**Comment by ProbablyGallium** [comment]
No worries, thanks for the help anyway!
